---
- name: "Processing user {{ item_user.name }} for {{ item_cloud.oscc_cloud|default(item_cloud.name) }} {{ item_cloud.region_name|default('') }}"
  os_user:
    cloud: "{{ item_cloud.oscc_cloud|default(item_cloud.name) }}"
    state: "{{ item_user.state|default(omit) }}"
    name: "{{ item_user.name }}"
    password: "{{ item_user.password }}"
    email: "{{ item_user.email|default(omit) }}"
    domain: "{{ item_user.domain|default(omit) }}"
    default_project: "{{ item_user.default_project|default(omit) }}"
    region_name: "{{ item_cloud.region_name|default(omit) }}"
    description: "{{ item_user.description|default(omit) }}"
    interface: "{{ item_cloud.interface|default(omit) }}"
    update_password: "{{ item_user.update_password|default(omit)}}"
