---
- name: "Processing subnet {{ item_subnet.name }} for {{ item_cloud.oscc_cloud|default(item_cloud.name) }} {{ item_cloud.region_name|default('') }}"
  os_subnet:
    cloud: "{{ item_cloud.oscc_cloud|default(item_cloud.name) }}"
    state: "{{ item_subnet.state|default(omit) }}"
    name: "{{ item_subnet.name }}"
    network_name: "{{ item_subnet.network_name|default(omit) }}"
    cidr: "{{ item_subnet.cidr }}"
    dns_nameservers: "{{ item_subnet.dns_nameservers|default(omit) }}"
    region_name: "{{ item_cloud.region_name|default(omit) }}"
    allocation_pool_end: "{{ item_subnet.allocation_pool_end|default(omit) }}"
    allocation_pool_start: "{{ item_subnet.allocation_pool_start|default(omit) }}"
    enable_dhcp: "{{ item_subnet.enable_dhcp|default(omit) }}"
    gateway_ip: "{{ item_subnet.gateway_ip|default(omit) }}"
    host_routes: "{{ item_subnet.host_routes|default(omit) }}"
    no_gateway_ip: "{{ item_subnet.no_gateway_ip|default(omit) }}"
    project: "{{ item_subnet.project|default(omit) }}"

